apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: default
spec:
  selector:
    io.kompose.service: app  # Match the pod's label exactly
  ports:
    - protocol: TCP
      port: 8080       # Port exposed by the Service
      targetPort: 8080 # Port exposed by the container
  type: ClusterIP       # Keep as ClusterIP for now