apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: default  # Change this if you are using a custom namespace
  labels:
    app: app
spec:
  replicas: 1  # Number of replicas for your application
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: stefanmrmov/devops_project:latest  # Replace 'app' with the correct Docker Hub image name
          ports:
            - containerPort: 8080  # Port exposed by your application inside the container
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: "33345"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/bookstore
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
          resources: {}  # Optional for resource limits/requests (can be removed if not needed)
      restartPolicy: Always