name: Build, Push, and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-push-deploy-k8s:
    name: Build, Push, and Deploy on Local Kubernetes
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Step 3: Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./labveb3/Dockerfile  # Path to your Dockerfile.
          push: true                  # Push image to Docker Hub.
          tags: stefanmrmov/devops_project:latest

      # Step 4: Deploy application on local Kubernetes cluster
      - name: Set up kubectl for local deployment
        run: |
          echo "Setting up kubectl..."
          mkdir -p ~/.kube/
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

      - name: Deploy Application to Local Kubernetes Cluster
        run: |
          kubectl apply -f k8s/ --validate=false